window.sitePartials = {
  header: [
    "<header class=\"site-header\">",
    "  <a class=\"brand\" href=\"#top\" aria-label=\"Home\">",
    "    <span class=\"brand-mark\">JN</span>",
    "    <span>Justus Njogu</span>",
    "  </a>",
    "  <button class=\"menu-button\" aria-expanded=\"false\" aria-controls=\"nav\">",
    "    Menu",
    "  </button>",
    "  <nav id=\"nav\" class=\"site-nav\" aria-label=\"Primary navigation\">",
    "    <a href=\"#work\">Work</a>",
    "    <a href=\"#skills\">Skills</a>",
    "    <a href=\"#certifications\">Certifications</a>",
    "    <a href=\"#about\">About</a>",
    "    <a class=\"nav-cta\" href=\"mailto:justusnjogu16@gmail.com\">Let's talk</a>",
    "  </nav>",
    "</header>",
    "",
  ].join("\n"),
  hero: [
    "<section id=\"top\" class=\"hero section-shell\">",
    "  <div class=\"eyebrow\">",
    "    <span class=\"status-dot\"></span>",
    "    Open to security opportunities",
    "  </div>",
    "  <div class=\"hero-grid\">",
    "    <div>",
    "      <p class=\"overline\">CYBERSECURITY PORTFOLIO / 2026</p>",
    "      <h1>I help teams <em>see</em> and reduce security risk.</h1>",
    "      <p class=\"hero-copy\">",
    "        I am Justus Njogu, an early-career cybersecurity professional building",
    "        hands-on experience in threat detection, vulnerability management,",
    "        network defense, and incident response.",
    "      </p>",
    "      <div class=\"hero-actions\">",
    "        <a class=\"button button-primary\" href=\"#work\">",
    "          Explore my work <span aria-hidden=\"true\">↘</span>",
    "        </a>",
    "        <a",
    "          class=\"button button-quiet\"",
    "          href=\"https://github.com/justo340\"",
    "          target=\"_blank\"",
    "          rel=\"noreferrer\"",
    "        >",
    "          GitHub <span aria-hidden=\"true\">↗</span>",
    "        </a>",
    "      </div>",
    "    </div>",
    "    <aside class=\"signal-card\" aria-label=\"Security focus areas\">",
    "      <div class=\"signal-top\">",
    "        <span>SECURITY SIGNAL</span>",
    "        <span>01 / 04</span>",
    "      </div>",
    "      <div class=\"signal-graphic\" aria-hidden=\"true\">",
    "        <i></i><i></i><i></i><i></i>",
    "        <i></i><i></i><i></i><i></i>",
    "      </div>",
    "      <div class=\"signal-bottom\">",
    "        <span>FOCUS AREAS</span>",
    "        <strong>Detection · Defense · Response</strong>",
    "      </div>",
    "    </aside>",
    "  </div>",
    "  <div class=\"trust-row\" aria-label=\"Portfolio highlights\">",
    "    <div>",
    "      <strong>Hands-on</strong>",
    "      <span>Labs &amp; home projects</span>",
    "    </div>",
    "    <div>",
    "      <strong>Evidence-led</strong>",
    "      <span>Clear methods &amp; outcomes</span>",
    "    </div>",
    "    <div>",
    "      <strong>Always learning</strong>",
    "      <span>New work added weekly</span>",
    "    </div>",
    "  </div>",
    "</section>",
    "",
  ].join("\n"),
  work: [
    "<section id=\"work\" class=\"section section-shell\">",
    "  <div class=\"section-intro\">",
    "    <p class=\"overline\">SELECTED WORK</p>",
    "    <h2>Proof, not just claims.</h2>",
    "    <p>",
    "      These projects load directly from my public GitHub profile. The newest",
    "      work appears here automatically, with links to the source and",
    "      documentation.",
    "    </p>",
    "  </div>",
    "  <p",
    "    id=\"projects-status\"",
    "    class=\"projects-status\"",
    "    role=\"status\"",
    "    aria-live=\"polite\"",
    "  >",
    "    Loading public projects from GitHub…",
    "  </p>",
    "  <div id=\"project-grid\" class=\"project-grid\" aria-live=\"polite\"></div>",
    "  <p class=\"portfolio-note\">",
    "    Only public, non-forked repositories are shown. Add clear repository",
    "    descriptions and README files so each card gives recruiters useful context.",
    "  </p>",
    "</section>",
    "",
  ].join("\n"),
  skills: [
    "<section id=\"skills\" class=\"skills-section\">",
    "  <div class=\"section-shell skills-layout\">",
    "    <div class=\"section-intro\">",
    "      <p class=\"overline\">SKILLSET</p>",
    "      <h2>A practical security foundation.</h2>",
    "      <p>Tools and methods I am actively applying in labs and projects.</p>",
    "    </div>",
    "    <div class=\"skill-list\">",
    "      <details open>",
    "        <summary><span>01</span>Threat detection <b>+</b></summary>",
    "        <p>",
    "          SIEM search, log analysis, alert triage, detection logic, and MITRE",
    "          ATT&amp;CK mapping.",
    "        </p>",
    "      </details>",
    "      <details>",
    "        <summary><span>02</span>Incident response <b>+</b></summary>",
    "        <p>",
    "          Scoping, evidence collection, timeline building, containment",
    "          recommendations, and clear incident notes.",
    "        </p>",
    "      </details>",
    "      <details>",
    "        <summary><span>03</span>Vulnerability management <b>+</b></summary>",
    "        <p>",
    "          Asset discovery, scanning, CVSS interpretation, risk-based",
    "          prioritization, and remediation tracking.",
    "        </p>",
    "      </details>",
    "      <details>",
    "        <summary><span>04</span>Network security <b>+</b></summary>",
    "        <p>",
    "          Traffic inspection, packet analysis, reconnaissance, firewall",
    "          fundamentals, and network segmentation.",
    "        </p>",
    "      </details>",
    "    </div>",
    "  </div>",
    "</section>",
    "",
  ].join("\n"),
  certifications: [
    "<section id=\"certifications\" class=\"section section-shell certifications-section\">",
    "  <div class=\"section-intro\">",
    "    <p class=\"overline\">CERTIFICATIONS</p>",
    "    <h2>Credentials that support my practice.</h2>",
    "    <p>",
    "      My certifications reflect the focused study and hands-on practice behind",
    "      my cybersecurity work. They support the labs, write-ups, and projects I",
    "      continue to build in this portfolio.",
    "    </p>",
    "    <a",
    "      class=\"button button-primary credential-cta\"",
    "      href=\"https://www.credly.com/users/justus-njogu/badges/credly\"",
    "      target=\"_blank\"",
    "      rel=\"noreferrer\"",
    "    >",
    "      View verified Credly badges <span aria-hidden=\"true\">↗</span>",
    "    </a>",
    "  </div>",
    "",
    "  <div class=\"certification-grid\">",
    "    <article class=\"certification-card\">",
    "      <span class=\"certification-number\">01</span>",
    "      <p class=\"overline\">EC-COUNCIL</p>",
    "      <h3>Certified Ethical Hacker (CEH)</h3>",
    "      <p>Issued May 2024 · Valid through May 2027</p>",
    "    </article>",
    "    <article class=\"certification-card\">",
    "      <span class=\"certification-number\">02</span>",
    "      <p class=\"overline\">CISCO</p>",
    "      <h3>Ethical Hacker</h3>",
    "      <p>Issued December 2024</p>",
    "    </article>",
    "    <article class=\"certification-card\">",
    "      <span class=\"certification-number\">03</span>",
    "      <p class=\"overline\">CISCO</p>",
    "      <h3>Cyber Threat Management</h3>",
    "      <p>Issued August 2023</p>",
    "    </article>",
    "  </div>",
    "</section>",
    "",
  ].join("\n"),
  profile: [
    "<section class=\"profile-section section-shell\" aria-labelledby=\"profile-title\">",
    "  <div class=\"profile-layout\">",
    "    <div class=\"profile-photo\">",
    "      <img",
    "        src=\"assets/profile.jpg\"",
    "        alt=\"Portrait of Justus Njogu\"",
    "      />",
    "    </div>",
    "    <div class=\"profile-content\">",
    "      <p class=\"overline\">PROFILE</p>",
    "      <h2 id=\"profile-title\">Justus Njogu</h2>",
    "      <p>",
    "        Certified cybersecurity analyst focused on practical security,",
    "        continuous learning, and hands-on technical work.",
    "      </p>",
    "      <a",
    "        class=\"text-link profile-link\"",
    "        href=\"https://www.linkedin.com/in/justus-njogu/\"",
    "        target=\"_blank\"",
    "        rel=\"noreferrer\"",
    "      >",
    "        View LinkedIn profile ↗",
    "      </a>",
    "    </div>",
    "  </div>",
    "</section>",
    "",
  ].join("\n"),
  about: [
    "<section id=\"about\" class=\"section section-shell about-section\">",
    "  <div class=\"about-statement\">",
    "    <p class=\"overline\">ABOUT ME</p>",
    "    <h2>Curious by nature. Methodical by practice.</h2>",
    "  </div>",
    "  <div class=\"about-copy\">",
    "    <p>",
    "      I am focused on the work that makes security operations dependable:",
    "      asking good questions, documenting evidence, and translating technical",
    "      findings into focused next steps.",
    "    </p>",
    "    <p>",
    "      This portfolio is a living record of that practice. Each week, I add",
    "      another lab, lesson, or project that shows what I can do.",
    "    </p>",
    "    <a class=\"text-link\" href=\"mailto:justusnjogu16@gmail.com\">",
    "      justusnjogu16@gmail.com <span aria-hidden=\"true\">↗</span>",
    "    </a>",
    "  </div>",
    "</section>",
    "",
  ].join("\n"),
  footer: [
    "<footer class=\"site-footer section-shell\">",
    "  <div>",
    "    <a class=\"brand\" href=\"#top\">",
    "      <span class=\"brand-mark\">JN</span>",
    "      <span>Justus Njogu</span>",
    "    </a>",
    "    <p>Cybersecurity portfolio · Built to grow with the work.</p>",
    "  </div>",
    "  <div class=\"footer-links\">",
    "    <a",
    "      href=\"https://www.linkedin.com/in/justus-njogu/\"",
    "      target=\"_blank\"",
    "      rel=\"noreferrer\"",
    "    >",
    "      LinkedIn ↗",
    "    </a>",
    "    <a href=\"https://github.com/justo340\" target=\"_blank\" rel=\"noreferrer\">",
    "      GitHub ↗",
    "    </a>",
    "    <a href=\"mailto:justusnjogu16@gmail.com\">Email ↗</a>",
    "  </div>",
    "  <p class=\"copyright\">© <span id=\"year\"></span> Justus Njogu</p>",
    "</footer>",
    "",
  ].join("\n"),
};
